In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score

In [2]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv'

In [3]:
!wget $data -O course_lead_scoring_2026.csv

--2026-09-28 08:03:25--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv

Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278746 (272K) [text/plain]
Saving to: ‘course_lead_scoring_2026.csv’

course_lead_scoring 100%[===================>] 272.21K  --.-KB/s    in 0.005s

2026-09-28 08:03:26 (54.1 MB/s) - ‘course_lead_scoring_2026.csv’ saved [278746/278746]

In [4]:
df = pd.read_csv('course_lead_scoring_2026.csv')

In [5]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [6]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [7]:
df.columns=df.columns.str.replace(' ','_').str.lower()

In [8]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [9]:
num_cols = df.select_dtypes(include=['number']).columns.drop(labels=['converted']).to_list()
num_cols

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [10]:
df[num_cols]

      annual_income  number_of_courses_viewed  interaction_count  lead_score
0           88160.0                         3                  4        0.64
1           72688.0                         3                  7        0.72
2           44697.0                         3                  4        0.58
3               NaN                         3                  6        0.57
4           24062.0                         4                  5        0.62
...             ...                       ...                ...         ...
4995        45834.0                         2                  2        0.37
4996        84831.0                         2                  5        0.51
4997        53636.0                         4                  6        0.75
4998        69430.0                         4                  8        0.79
4999        81355.0                         6                 11        0.99

[5000 rows x 4 columns]

In [11]:
df[num_cols] = df[num_cols].fillna(0.0)

In [12]:
cat_cols = df.select_dtypes(exclude=['number']).columns.to_list()
cat_cols

['lead_source', 'industry', 'employment_status', 'location']

In [13]:
# for col in cat_cols:
#    df[col] = df[col].str.lower().str.replace(' ', '_')

In [14]:
df[cat_cols] = df[cat_cols].fillna('NA')

In [15]:
df['industry'].describe()

count           5000
unique             7
top       technology
freq            1173
Name: industry, dtype: object

In [16]:
df_full_train, df_test = train_test_split(df,test_size=0.2,random_state=42)
df_train, df_val = train_test_split(df_full_train,test_size=0.25,random_state=42)

In [17]:
len(df_train),len(df_val), len(df_test)

(3000, 1000, 1000)

In [18]:
df_full_train = df_full_train.reset_index(drop=True)
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [19]:
y_full_train = df_full_train.converted.values
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values
y_train

array([1, 0, 1, ..., 1, 0, 0], shape=(3000,))

In [20]:
df_train = df_train.drop(columns=['converted'])
df_val = df_val.drop(columns=['converted'])
df_test = df_test.drop(columns=['converted'])

In [21]:
df_full_train[num_cols].corrwith(df_full_train.converted)

annual_income               0.188437
number_of_courses_viewed    0.393200
interaction_count           0.450273
lead_score                  0.482078
dtype: float64

In [22]:
df_full_train[['interaction_count']].corrwith(df_full_train.lead_score)

interaction_count    0.916626
dtype: float64

In [23]:
df_full_train[['number_of_courses_viewed']].corrwith(df_full_train.lead_score)

number_of_courses_viewed    0.757178
dtype: float64

In [24]:
df_full_train[['number_of_courses_viewed']].corrwith(df_full_train.interaction_count)

number_of_courses_viewed    0.72304
dtype: float64

In [25]:
df_full_train[['annual_income']].corrwith(df_full_train.interaction_count)

annual_income    0.122528
dtype: float64

In [26]:
df_full_train.converted.value_counts(normalize=True)

converted
1    0.57075
0    0.42925
Name: proportion, dtype: float64

In [27]:
global_converted = df_full_train.converted.mean()
global_converted

np.float64(0.57075)

In [28]:
lead_score_converted = df_full_train.lead_score.mean()
interaction_count_converted = df_full_train.interaction_count.mean()
number_of_courses_viewed_converted = df_full_train.number_of_courses_viewed.mean()
annual_income_converted = df_full_train.annual_income.mean()

In [29]:
def mutual_info_converted_score(series):
    return round(mutual_info_score(series, df_full_train.converted),2)

In [30]:
mi = df_full_train[cat_cols].apply(mutual_info_converted_score)
mi.sort_values(ascending=False)

lead_source          0.03
employment_status    0.02
industry             0.00
location             0.00
dtype: float64

In [31]:
train_dicts = df_train[cat_cols + num_cols].to_dict(orient='records')
val_dicts = df_val[cat_cols + num_cols].to_dict(orient='records')

In [32]:
from sklearn.feature_extraction import DictVectorizer

In [33]:
dv = DictVectorizer(sparse=False)

In [34]:
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

In [35]:
X_train.shape

(3000, 28)

In [36]:
dv.get_feature_names_out()

array(['annual_income', 'employment_status=NA',
       'employment_status=employed', 'employment_status=self_employed',
       'employment_status=student', 'employment_status=unemployed',
       'industry=NA', 'industry=education', 'industry=finance',
       'industry=healthcare', 'industry=manufacturing', 'industry=retail',
       'industry=technology', 'interaction_count', 'lead_score',
       'lead_source=NA', 'lead_source=events',
       'lead_source=organic_search', 'lead_source=paid_ads',
       'lead_source=referral', 'lead_source=social_media', 'location=NA',
       'location=africa', 'location=asia', 'location=europe',
       'location=north_america', 'location=south_america',
       'number_of_courses_viewed'], dtype=object)

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
y_train

array([1, 0, 1, ..., 1, 0, 0], shape=(3000,))

In [39]:
X_train

array([[6.5980e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       [7.1662e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [4.0220e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+00],
       ...,
       [7.1532e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [4.8836e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [6.8969e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]], shape=(3000, 28))

In [40]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [41]:
model.intercept_[0]

np.float64(-0.010838978497809095)

In [42]:
model.coef_[0].round(3)

array([-0.   , -0.001,  0.007, -0.003, -0.008, -0.006, -0.   , -0.003,
       -0.001, -0.002, -0.002, -0.002, -0.001,  0.137,  0.011,  0.   ,
       -0.009,  0.007, -0.014,  0.009, -0.004,  0.   , -0.002, -0.002,
       -0.001, -0.003, -0.004,  0.054])

In [43]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred

array([0.61725691, 0.44364108, 0.60433996, 0.64562246, 0.52214159,
       0.77885722, 0.60698076, 0.54481903, 0.76770971, 0.52765495,
       0.75038798, 0.6470054 , 0.56857815, 0.51044645, 0.59921425,
       0.46620745, 0.62786484, 0.69167143, 0.69082953, 0.59101344,
       0.49964695, 0.55590822, 0.65303933, 0.6079306 , 0.7231576 ,
       0.51616805, 0.56141276, 0.57206269, 0.67043904, 0.55599224,
       0.63613322, 0.70337215, 0.45463513, 0.61897288, 0.65250689,
       0.42775649, 0.63943096, 0.62315373, 0.6602988 , 0.51736304,
       0.53774147, 0.76074014, 0.48326071, 0.74151288, 0.63662375,
       0.41194601, 0.45371292, 0.6417333 , 0.43851314, 0.87060984,
       0.72468973, 0.75643941, 0.5296636 , 0.66736678, 0.50444495,
       0.57644782, 0.72318139, 0.72497254, 0.6507741 , 0.628958  ,
       0.7217776 , 0.59231588, 0.70824617, 0.61451576, 0.49691434,
       0.74445314, 0.52773381, 0.61402574, 0.55979831, 0.59024431,
       0.69368703, 0.72962242, 0.76111566, 0.60744404, 0.52501652,
       0.56663775, 0.57985465, 0.44874343, 0.55832072, 0.63621002,
       0.64527742, 0.77774815, 0.69509048, 0.72441146, 0.61956857,
       0.56238173, 0.67485361, 0.68497031, 0.49826753, 0.74320605,
       0.62159939, 0.62303598, 0.6032927 , 0.59863787, 0.67381217,
       0.629014  , 0.68392655, 0.68566135, 0.70812817, 0.65760045,
       0.62879618, 0.61464867, 0.60170905, 0.55517109, 0.63638247,
       0.67666793, 0.72736362, 0.55497829, 0.61757328, 0.52714432,
       0.74592812, 0.51303943, 0.71511379, 0.63900779, 0.75413385,
       0.59537619, 0.46187073, 0.68451445, 0.60860326, 0.69183184,
       0.7223153 , 0.57987312, 0.61589153, 0.53954781, 0.64263963,
       0.54313054, 0.48010457, 0.43089808, 0.66375434, 0.54856487,
       0.42658218, 0.61717316, 0.47437104, 0.66131919, 0.54492307,
       0.59923268, 0.59675716, 0.65892172, 0.74065616, 0.57362147,
       0.63103897, 0.49603008, 0.52380925, 0.73687908, 0.49705183,
       0.74183732, 0.70145254, 0.77958252, 0.59243939, 0.75645573,
       0.65305367, 0.62967105, 0.64453568, 0.44449072, 0.60605741,
       0.62752799, 0.62772717, 0.49201181, 0.50654831, 0.788552  ,
       0.55956805, 0.63111809, 0.63218463, 0.7410883 , 0.67886348,
       0.65960705, 0.64231711, 0.49022198, 0.60692902, 0.58156181,
       0.54394978, 0.6855123 , 0.69579723, 0.70728329, 0.54670762,
       0.39971096, 0.72845662, 0.65675367, 0.54514254, 0.60978015,
       0.79275239, 0.58722404, 0.63913944, 0.74500605, 0.54712647,
       0.65672074, 0.6290638 , 0.64785649, 0.5941468 , 0.67110453,
       0.65449323, 0.58383061, 0.70517717, 0.75134332, 0.49912469,
       0.62907645, 0.44257632, 0.66934614, 0.62511857, 0.75803588,
       0.65638903, 0.54701222, 0.69159571, 0.5506639 , 0.41763743,
       0.44857036, 0.62320802, 0.56380287, 0.61216073, 0.79886471,
       0.80117478, 0.62888192, 0.6562283 , 0.67562725, 0.67752284,
       0.57019307, 0.49671121, 0.67789486, 0.65780537, 0.75001586,
       0.62427127, 0.61304663, 0.59873525, 0.62034593, 0.64899345,
       0.6766309 , 0.55049307, 0.49704654, 0.43803786, 0.50064321,
       0.7273225 , 0.79181718, 0.52155639, 0.62664108, 0.73181221,
       0.59511554, 0.60715185, 0.51154731, 0.52628898, 0.56999231,
       0.55513276, 0.64641264, 0.64226501, 0.67316153, 0.71982105,
       0.75424476, 0.5156686 , 0.61241603, 0.47448838, 0.67751216,
       0.56610995, 0.55065818, 0.53910955, 0.41346738, 0.7988097 ,
       0.62864551, 0.6528224 , 0.70254901, 0.63093597, 0.66690738,
       0.64273492, 0.67631641, 0.67787979, 0.64034474, 0.70732255,
       0.5097563 , 0.62428947, 0.58827967, 0.44002129, 0.6350843 ,
       0.547679  , 0.65738831, 0.58013385, 0.60833086, 0.75241618,
       0.67705311, 0.73149533, 0.56444766, 0.62590473, 0.49778179,
       0.63942557, 0.63610883, 0.58515358, 0.67314157, 0.67342863,
       0.61102758, 0.62735948, 0.6177127 , 0.65743941, 0.63138296,
       0.83015979, 0.54553322, 0.50570915, 0.64133082, 0.58828518,
       0.70092172, 0.5645042 , 0.48025437, 0.63749436, 0.56922819,
       0.64848424, 0.64900372, 0.58926105, 0.78537188, 0.59192072,
       0.7047046 , 0.79923239, 0.76206452, 0.57119276, 0.70244351,
       0.48959781, 0.42668858, 0.58632782, 0.55402067, 0.55229694,
       0.58079551, 0.70880182, 0.6381247 , 0.70524127, 0.5610224 ,
       0.66472486, 0.61289426, 0.57970052, 0.59020359, 0.46594052,
       0.79133405, 0.54700727, 0.7676266 , 0.67035652, 0.81457548,
       0.66502376, 0.62749361, 0.65005177, 0.60821543, 0.58951267,
       0.61924824, 0.58949811, 0.64643971, 0.52643444, 0.71372385,
       0.66797119, 0.69958422, 0.41803286, 0.71471053, 0.59921948,
       0.66961814, 0.68479134, 0.58109567, 0.73388885, 0.72592467,
       0.59535305, 0.47075341, 0.68653535, 0.60484288, 0.67738643,
       0.44145722, 0.62776888, 0.6692684 , 0.63783561, 0.75220009,
       0.77706691, 0.48183336, 0.76704076, 0.57840446, 0.74423607,
       0.71617399, 0.59735407, 0.49933892, 0.60039015, 0.70219478,
       0.6928125 , 0.568783  , 0.46047751, 0.70829101, 0.63668591,
       0.70449231, 0.6915663 , 0.49283177, 0.49527528, 0.60909843,
       0.57251182, 0.76015098, 0.69089538, 0.59990745, 0.53593536,
       0.66852441, 0.54238036, 0.42319032, 0.62172185, 0.50531211,
       0.58210429, 0.48224264, 0.54618198, 0.56967121, 0.68884884,
       0.580896  , 0.7318566 , 0.72092826, 0.6381895 , 0.68153348,
       0.5879502 , 0.72668707, 0.49000443, 0.65985333, 0.76136375,
       0.71774683, 0.52610759, 0.72203156, 0.57693597, 0.62789766,
       0.69727529, 0.63406388, 0.6659835 , 0.62595163, 0.50209161,
       0.69780439, 0.77457301, 0.68883337, 0.53231528, 0.53612824,
       0.46160959, 0.77750282, 0.43487097, 0.59834384, 0.65892163,
       0.8000846 , 0.72615612, 0.54723949, 0.79577553, 0.55728311,
       0.62280117, 0.59968786, 0.61839225, 0.67992397, 0.62176395,
       0.70059687, 0.66169417, 0.46475178, 0.51191523, 0.45545271,
       0.59591783, 0.71324349, 0.44162329, 0.70134176, 0.66028499,
       0.49510951, 0.71959792, 0.53131584, 0.67579686, 0.61600929,
       0.6320944 , 0.66719075, 0.67366342, 0.47671892, 0.60360615,
       0.52951146, 0.60149085, 0.86096465, 0.46103257, 0.61345308,
       0.68408405, 0.77749072, 0.58904891, 0.60191186, 0.6925575 ,
       0.67612544, 0.46113028, 0.65112546, 0.58631194, 0.53649406,
       0.60732083, 0.67883106, 0.63079655, 0.59806084, 0.62373264,
       0.65065996, 0.72112821, 0.64771098, 0.74829465, 0.57384315,
       0.72073922, 0.64195563, 0.63838909, 0.44748342, 0.59939635,
       0.60093154, 0.69003993, 0.67455301, 0.54103524, 0.47381782,
       0.73454401, 0.65839125, 0.69264949, 0.65790359, 0.50495224,
       0.63245252, 0.65485423, 0.56114197, 0.67858783, 0.50497349,
       0.60890036, 0.6706332 , 0.67793648, 0.54934079, 0.64162225,
       0.54759594, 0.61921626, 0.65272143, 0.6893685 , 0.69899421,
       0.51496718, 0.66773497, 0.46139207, 0.52479035, 0.66726955,
       0.49158008, 0.54065119, 0.59017253, 0.50365921, 0.57971135,
       0.70208414, 0.75700387, 0.56447986, 0.64517879, 0.59189532,
       0.69277636, 0.60532491, 0.54492475, 0.4930172 , 0.59078357,
       0.68799765, 0.5096362 , 0.60002193, 0.71728414, 0.46635538,
       0.5744293 , 0.62408004, 0.63635527, 0.67992734, 0.64958444,
       0.69812067, 0.49478741, 0.76306022, 0.50113931, 0.72392493,
       0.51249502, 0.74718109, 0.53361453, 0.49044097, 0.53314238,
       0.50346164, 0.59975012, 0.73059457, 0.69739926, 0.54813086,
       0.5548334 , 0.51108951, 0.58986918, 0.47715187, 0.70126896,
       0.48878298, 0.63836619, 0.58075005, 0.45832458, 0.67509813,
       0.7098609 , 0.6368074 , 0.54852883, 0.65554623, 0.68071014,
       0.44770377, 0.70049316, 0.53080932, 0.39820946, 0.67527318,
       0.70605845, 0.63146346, 0.83829227, 0.57032208, 0.67000565,
       0.65138325, 0.66112763, 0.54537844, 0.61813601, 0.57785267,
       0.73919298, 0.68174693, 0.42187579, 0.64363706, 0.65731158,
       0.70541665, 0.62811488, 0.66816554, 0.64034907, 0.77911595,
       0.54298445, 0.63835543, 0.66562182, 0.64085511, 0.52713001,
       0.57570666, 0.79960361, 0.66983556, 0.6435138 , 0.68329495,
       0.65975227, 0.42724219, 0.71628302, 0.5455977 , 0.55506714,
       0.5605923 , 0.62384449, 0.49067178, 0.73598033, 0.50675408,
       0.64461687, 0.50908228, 0.6263749 , 0.67391424, 0.6830949 ,
       0.59601293, 0.64332949, 0.48229654, 0.60720617, 0.55612432,
       0.71753945, 0.60269265, 0.5709283 , 0.60224134, 0.48346375,
       0.74861062, 0.73535617, 0.63545104, 0.67928643, 0.53949574,
       0.63178254, 0.50725652, 0.60908787, 0.72666773, 0.43037732,
       0.60666355, 0.55825757, 0.51495447, 0.6394762 , 0.67499696,
       0.61381667, 0.65609538, 0.48438435, 0.68713794, 0.69856585,
       0.5687532 , 0.65301785, 0.56993588, 0.61267664, 0.60093577,
       0.47270406, 0.50886529, 0.59578613, 0.5715621 , 0.65295554,
       0.59558969, 0.46731922, 0.52946416, 0.68974107, 0.457083  ,
       0.68588603, 0.63007581, 0.58570226, 0.67009231, 0.67642925,
       0.60668988, 0.59736924, 0.67395364, 0.54068637, 0.62161892,
       0.6148961 , 0.76060097, 0.72386733, 0.75014928, 0.59336878,
       0.58842987, 0.56433634, 0.74509584, 0.47136169, 0.52963984,
       0.45722398, 0.63859417, 0.58982118, 0.67058317, 0.5947875 ,
       0.42709864, 0.5626221 , 0.73796885, 0.60869885, 0.73208354,
       0.53750712, 0.76561237, 0.45043585, 0.46930642, 0.55318395,
       0.72367643, 0.79482576, 0.77388569, 0.71566726, 0.60669355,
       0.54168481, 0.48897245, 0.69997023, 0.60695014, 0.52280827,
       0.46561681, 0.52792109, 0.60468019, 0.7234566 , 0.57885946,
       0.61178445, 0.45637165, 0.46111287, 0.56748665, 0.63727841,
       0.61038083, 0.82294132, 0.69484083, 0.81132958, 0.56371495,
       0.44344111, 0.62969027, 0.59534047, 0.48407248, 0.55425722,
       0.58724999, 0.82017108, 0.78282135, 0.58609957, 0.58080263,
       0.51704537, 0.56686509, 0.56753922, 0.66509367, 0.49756768,
       0.53505736, 0.5399085 , 0.51754751, 0.66431676, 0.48275308,
       0.65656974, 0.58250942, 0.47933534, 0.67275311, 0.70580344,
       0.5054256 , 0.65102941, 0.6112546 , 0.48262142, 0.55933467,
       0.78162187, 0.57812082, 0.62117794, 0.55512498, 0.66348194,
       0.70041463, 0.70775097, 0.75989311, 0.55894633, 0.81257814,
       0.67287104, 0.63178995, 0.69864918, 0.53572311, 0.64095504,
       0.65968826, 0.67187544, 0.7916359 , 0.55164812, 0.66767819,
       0.42592274, 0.67301766, 0.66346561, 0.54231525, 0.49267642,
       0.49389189, 0.67875794, 0.58429036, 0.57322147, 0.42074843,
       0.64977664, 0.57641374, 0.6724851 , 0.54761947, 0.59305818,
       0.53707273, 0.71512544, 0.62177238, 0.64695118, 0.55485348,
       0.65354146, 0.71620548, 0.54614889, 0.62650956, 0.4681912 ,
       0.6320503 , 0.7455898 , 0.7727857 , 0.5924923 , 0.76067382,
       0.74233924, 0.50663823, 0.64496116, 0.68454857, 0.59582058,
       0.77536493, 0.5514313 , 0.68139667, 0.50716817, 0.48916207,
       0.58043032, 0.78922952, 0.69326023, 0.55555846, 0.59364929,
       0.46163262, 0.71397377, 0.59512919, 0.62993746, 0.56046881,
       0.66629764, 0.5105088 , 0.68959771, 0.63600644, 0.55334731,
       0.49546045, 0.57473   , 0.4697132 , 0.54130289, 0.53931262,
       0.64951384, 0.66810299, 0.71035326, 0.68316932, 0.58068423,
       0.63841337, 0.57327616, 0.47286108, 0.64810689, 0.57284925,
       0.54438784, 0.73087823, 0.46057763, 0.7032285 , 0.62554201,
       0.62939466, 0.7783214 , 0.70478034, 0.63475958, 0.57678284,
       0.57274681, 0.52292362, 0.61985259, 0.57811021, 0.55769489,
       0.70479735, 0.44436997, 0.67318979, 0.52273346, 0.62219978,
       0.54440958, 0.58930871, 0.67388996, 0.5476109 , 0.64431428,
       0.47354341, 0.61827346, 0.65256659, 0.65530004, 0.52510687,
       0.61615504, 0.46898201, 0.4877836 , 0.60482003, 0.67921514,
       0.71252904, 0.55122215, 0.62263792, 0.4575969 , 0.51919724,
       0.45508829, 0.5535923 , 0.53389804, 0.68503262, 0.53340705,
       0.69328699, 0.50186968, 0.543851  , 0.7014969 , 0.55120888,
       0.55271606, 0.50459382, 0.49093174, 0.58108109, 0.58992105,
       0.71286711, 0.56484627, 0.66825059, 0.77983694, 0.72442071,
       0.49492029, 0.59593039, 0.65048093, 0.57076383, 0.65490362,
       0.61472545, 0.80074573, 0.67137364, 0.52576789, 0.60791268,
       0.5649506 , 0.45400291, 0.68621028, 0.52491556, 0.74093087,
       0.66843522, 0.65399557, 0.55052712, 0.71466275, 0.61865883,
       0.48654035, 0.50810116, 0.60089307, 0.66307953, 0.6919697 ,
       0.59214372, 0.43020854, 0.63864104, 0.60980297, 0.52302809,
       0.51344417, 0.50005249, 0.62923927, 0.48933854, 0.62643246,
       0.60748024, 0.66329379, 0.66065462, 0.66059418, 0.70431597,
       0.7250103 , 0.50092491, 0.67304148, 0.63606935, 0.58599886,
       0.69913084, 0.68069352, 0.70393274, 0.81278319, 0.66126558,
       0.68003396, 0.65385909, 0.6778914 , 0.74447276, 0.63331982,
       0.48513477, 0.67383274, 0.63046037, 0.7723645 , 0.72239548,
       0.48174844, 0.64022587, 0.58566432, 0.6168071 , 0.71036155,
       0.55626757, 0.52248669, 0.42900052, 0.5885622 , 0.74700506,
       0.79781925, 0.64155448, 0.66686727, 0.47058986, 0.5507701 ,
       0.50731084, 0.74287894, 0.60903961, 0.59382504, 0.60406156,
       0.57083111, 0.63984295, 0.6850845 , 0.66306542, 0.42981949,
       0.4625138 , 0.57073756, 0.54397444, 0.61261575, 0.66531311,
       0.68471025, 0.66957957, 0.45847265, 0.56177032, 0.58728419])

In [44]:
converted_decision = (y_pred>=0.5)

In [45]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = converted_decision.astype(int)
df_pred['actual'] = y_val
df_pred['correct'] = df_pred.prediction == df_pred.actual

In [46]:
df_pred

     probability  prediction  actual  correct
0       0.617257           1       1     True
1       0.443641           0       1    False
2       0.604340           1       0    False
3       0.645622           1       1     True
4       0.522142           1       0    False
..           ...         ...     ...      ...
995     0.684710           1       1     True
996     0.669580           1       1     True
997     0.458473           0       0     True
998     0.561770           1       0    False
999     0.587284           1       1     True

[1000 rows x 4 columns]

In [47]:
accuracy = round(df_pred.correct.mean(), 2)
accuracy

np.float64(0.64)

In [48]:
y_train

array([1, 0, 1, ..., 1, 0, 0], shape=(3000,))

In [55]:
features = cat_cols + num_cols
diffs = {}

train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_val)
baseline_acc = (y_val == y_pred).mean()

for feature in features:
    selected = [f for f in features if f != feature]
    
    train_dicts_sel = df_train[selected].to_dict(orient='records')
    val_dicts_sel = df_val[selected].to_dict(orient='records')

    dv_sel = DictVectorizer(sparse=False)
    X_train_sel = dv_sel.fit_transform(train_dicts_sel)
    X_val_sel = dv_sel.transform(val_dicts_sel)

    model_sel = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model_sel.fit(X_train_sel, y_train)

    y_pred_sel = model_sel.predict_proba(X_val_sel)[:, 1]
    converted_decision_sel = (y_pred_sel >= 0.5)
    # converted_decision_sel = model_sel.predict(X_val_sel)
    
    accuracy_sel = (converted_decision_sel.astype(int) == y_val).mean()
    diffs[feature] = baseline_acc - accuracy_sel

for f, diff in diffs.items():
    print(f"{f}: {diff:.4f}")

lead_source: 0.0030
industry: 0.0000
employment_status: 0.0000
location: 0.0000
annual_income: -0.0790
number_of_courses_viewed: 0.0020
interaction_count: 0.0440
lead_score: 0.0010

In [58]:
c_values = [0.000001, 0.00001, 0.0001, 0.001]

features = cat_cols + num_cols
diffs = {}

train_dicts = df_train[features].to_dict(orient='records')
val_dicts = df_val[features].to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

for c in c_values:
  model = LogisticRegression(solver='liblinear', C=c, max_iter=1000, random_state=42)
  model.fit(X_train, y_train)

  y_pred = model.predict(X_val)
  acc = round((y_val == y_pred).mean(), 3)
  print(f"c: {c} accuracy: {acc}")

c: 1e-06 accuracy: 0.598
c: 1e-05 accuracy: 0.598
c: 0.0001 accuracy: 0.613
c: 0.001 accuracy: 0.645